# SiliconCompiler Development Environment
#
# Use the latest stable Python image
FROM ubuntu:22.04

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git sudo build-essential \
    python3-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Clone SiliconCompiler repository
WORKDIR /opt
RUN git clone https://github.com/siliconcompiler/siliconcompiler

# Set working directory
WORKDIR /opt/siliconcompiler

# Upgrade pip and install SiliconCompiler
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir .
RUN pip3 list
RUN sc-install openroad
RUN sc-install klayout
RUN sc-install yosys
RUN sc-install sv2v
RUN sc-install yosys-slang

# Default shell
CMD ["/bin/bash"]
